### PR TITLE
update websocket to v2.1.0 and enable ssl

### PR DESCRIPTION
**Pull request by minggo**

### CODE REVIEW

**Comment by minggo** [comment]
@stammen we are upgrading websockets to v2.1.0 and enable ssl because iOS requires ssl support. Could you please help to update the winrt and wp platform? 

Thanks.

**Comment by stammen** [comment]
I can do this after I return to Seattle on Jan 9.

**Comment by minggo** [comment]
Thanks. But we may release it before Jan 9, so we may let winrt and wp not support ssl.

**Comment by stammen** [comment]
No ssl support for winrt platforms would be fine. I will update the code as soon as I can after Jan 9.

**Comment by minggo** [comment]
Thanks.

**Pull request merged**
