### PR TITLE
Install zlibstatic.lib

### PR DESCRIPTION
**Pull request by steerlink**
Open up the option to link statically.

@stammen @zilongshanren

### CODE REVIEW

**Comment by zilongshanren** [comment]
@steerlink  thanks. it looks good to me
@stammen  Thoughts?

**Comment by steerlink** [comment]
Can this get merged? @stammen @zilongshanren

**Comment by stammen** [comment]
@steerlink It is already part of the dependencies

https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/tree/v3/win10-specific/zlib/prebuilt/win32

I am updating the build system and your change is part of that. The changes are here:

https://github.com/Microsoft/cocos2d-x-3rd-party-libs-src

**Comment by steerlink** [comment]
@stammen When are you going to merge changes from your forked repo into this repo? It seems like this PR is still valid since your changes aren't in here yet.

**Comment by stammen** [comment]
@steerlink I have updated this repo to build the Win10 UWP dependencies using https://github.com/Microsoft/vcpkg. zlibstatic is part of the build.

**Comment by steerlink** [comment]
Thanks @stammen

**Pull request closed without merging**
