### PR TITLE
Merge ms repo

### PR DESCRIPTION
**Pull request by zilongshanren**

### CODE REVIEW

**Comment by zilongshanren** [comment]
@ricardoquesada please review...

**Comment by ricardoquesada** [comment]
looks good. can you squash it in just one commit ? thanks.

**Comment by zilongshanren** [comment]
@ricardoquesada  done at https://github.com/cocos2d/cocos2d-x-3rd-party-libs-src/pull/93

**Comment by ricardoquesada** [comment]
thanks!

**Pull request closed without merging**
