### PR TITLE
Update curl and openssl

### PR DESCRIPTION
**Pull request by steerlink**
Use the latest curl and openssl libraries.

### CODE REVIEW

**Comment by zilongshanren** [comment]
@steerlink  thanks， when we decide to upgrade the curl and openssl library， I will merge this PR.

**Comment by pixmaster** [comment]
current openssl v1.0.2f

**Comment by minggo** [comment]
@zilongshanren I think we should upgrade to latest version if possible.

**Comment by zilongshanren** [comment]
@minggo  The latest version is 1.02g, I will send a pull request later.

**Comment by zilongshanren** [comment]
@minggo  And the CURL version is 7.48

**Comment by minggo** [comment]
@zilongshanren Can we just upgrade OpenSSL without upgrading CURL?

**Comment by zilongshanren** [comment]
@minggo sure... But this PR also contain the CURL upgrade... Thoughts?

**Comment by minggo** [comment]
I think it is not problem.

**Comment by minggo** [comment]
Of course, we should make sure that CURL upgrading will not break compatibility, or should should not upgrade it, because we don't plan to upgrade CURL in v3.11.

**Pull request merged**
